export class PASSWORDRULE {
  public static datePosition = [
    'DDMMYYYY',
    'DDYYYYMM',
    'MMDDYYYY',
    'MMYYYYDD',
    'YYYYDDMM',
    'YYYYMMDD',
    'DDMMYY',
    'DDYYMM',
    'MMDDYY',
    'MMYYDD',
    'YYDDMM',
    'YYMMDD',
    'DMMYY',
    'DYYMM',
    'MMDYY',
    'MMYYD',
    'YYDMM',
    'YYMMD',
    'DMMYYYY',
    'DYYYYMM',
    'MMDYYYY',
    'MMYYYYD',
    'YYYYDMM',
    'YYYYMMD',
    'DMYYYY',
    'DYYYYM',
    'MDYYYY',
    'MYYYYD',
    'YYYYDM',
    'YYYYMD',
    'DMYY',
    'DYYM',
    'MDYY',
    'MYYD',
    'YYDM',
    'YYMD',
    'DDMYY',
    'DDYYM',
    'MDDYY',
    'MYYDD',
    'YYDDM',
    'YYMDD',
    'DDMYYYY',
    'DDYYYYM',
    'MDDYYYY',
    'MYYYYDD',
    'YYYYDDM',
    'YYYYMDD',
  ];

  public static rule = {
    e: ['3'],
    t: ['7'],
    i: ['1', '!'],
    o: ['0'],
    a: ['@'],
    g: ['9'],
    l: ['7'],
    z: ['2'],
    b: ['8', '6'],
  };

  public static numberRule = {
    1: ['i', 'I', 'l', '!'],
    2: ['z', 'Z'],
    3: ['e, E'],
    5: ['s', 'S'],
    6: ['b'],
    7: ['L'],
    8: ['B'],
    9: ['g'],
  };

  public static matrix = [
    {
      firstVal: 'firstname',
      lastname: true,
      birthday: true,
      address: true,
      hobby: true,
      childrenName: true,
      wifeName: true,
      job: true,
    },
    {
      firstVal: 'lastname',
      firstname: true,
      birthday: true,
      address: true,
      wifeName: true,
      job: true,
    },
    {
      firstVal: 'birthday',
      firstname: true,
      lastname: true,
      wifeName: true,
      job: true,
    },
    {
      firstVal: 'address',
      firstname: true,
      lastname: true,
      hobby: true,
      childrenName: true,
      wifeName: true,
      job: true,
    },
    {
      firstVal: 'hobby',
      firstname: true,
      address: true,
      childrenName: true,
      wifeName: true,
      job: true,
    },
    {
      firstVal: 'childrenName',
      firstname: true,
      address: true,
      hobby: true,
      wifeName: true,
    },
    {
      firstVal: 'wifeName',
      firstname: true,
      lastname: true,
      birthday: true,
      address: true,
      hobby: true,
      childrenName: true,
    },
    {
      firstVal: 'job',
      firstname: true,
      lastname: true,
      birthday: true,
      address: true,
      hobby: true,
    },
  ];
}
